# Oh My Zsh framework
# https://github.com/ohmyzsh/ohmyzsh
[".local/opt/ohmyzsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod = "168h"

# Zsh autosuggestions plugin (Oh My Zsh custom plugin)
# https://github.com/zsh-users/zsh-autosuggestions
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod = "168h"
