query($owner: String!, $repo: String!, $pr: Int!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $pr) {
      number
      title
      url
      reviewThreads(first: 100) {
        totalCount
        nodes {
          id
          isResolved
          isOutdated
          path
          line
          originalLine
          resolvedBy {
            login
          }
          comments(first: 100) {
            totalCount
            nodes {
              id
              author {
                login
              }
              createdAt
              body
              url
            }
          }
        }
      }
    }
  }
}
