version = 1

# Global defaults
[*]
models-max = 1
threads = 12
cache-type-k = q4_0
cache-type-v = q4_0
flash-attn = true
jinja = true
no-context-shift = true

# Alias: gemma-4
[gemma-4-e4b]
hf-repo = bartowski/google_gemma-4-E4B-it-GGUF
hf-file = google_gemma-4-E4B-it-Q4_K_M.gguf
ctx-size = 16000
ngl = 0

# Alias: qwen-35b
[qwen-35b]
hf-repo = bartowski/Qwen_Qwen3.6-35B-A3B-GGUF
hf-file = Qwen_Qwen3.6-35B-A3B-IQ3_XXS.gguf
ctx-size = 16000
ngl = 0

# Alias: qwopus
[qwopus-3.5-9b]
hf-repo = Jackrong/Qwopus3.5-9B-v3-GGUF
hf-file = Qwopus3.5-9B-v3.Q4_K_M.gguf
ctx-size = 32000
ngl = 0
