#!/usr/bin/env bash
# Another traffic sniffer
hash pygmentize 2>/dev/null || { echo 'Please install with `pip install Pygments`'; exit;}


if [ -t 0 ]; then # argument
    python3 -mjson.tool <<< "$*" | pygmentize -l javascript;
else # pipe
	python3 -mjson.tool | pygmentize -l javascript;
fi;
