name: 🐞 Bug Report
description: Report a bug or unexpected behavior in the dotfiles configuration.
title: "🐞 bug: <title>"
labels: [bug, needs-triage]
body:

  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description of what is happening. Include any error messages.
      placeholder: |
        When I run `some-command`, I get the following error:
        ```
        error message here
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Open a new terminal
        2. Run `source ~/.zshrc`
        3. Run `command-name`
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment Details
      description: Please provide information about your environment.
      value: |
        - **Zsh Version**: <!-- output of `zsh --version` -->
        - **OS/Distro**: <!-- e.g., Ubuntu 24.04, Arch Linux, macOS 14 -->
        - **Terminal**: <!-- e.g., Alacritty, iTerm2, Kitty, GNOME Terminal -->
    validations:
      required: true

  - type: textarea
    attributes:
      label: Relevant Configuration
      description: |
        If applicable, share any relevant snippets from your configuration.
        Please redact any sensitive information (API keys, paths, etc.).
      render: shell

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help.
