name: 💡 Feature Request
description: Suggest a new feature or improvement for the dotfiles configuration.
title: "💡 feat: <title>"
labels: [enhancement]
body:

  - type: textarea
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the frustration or limitation.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: A clear description of what you want to happen.
      placeholder: |
        I would like a new function `foo.bar` that does X when called with Y.
        
        Example usage:
        ```zsh
        foo.bar --option value
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples that would help illustrate the feature.
