[bootstrap.packages]
# --- Personal Apps ---
# ffmpeg
"apt:ffmpeg"    = "latest"
"dnf:ffmpeg"    = "latest"
"pacman:ffmpeg" = "latest"
"brew:ffmpeg"   = "latest"

# k8slens
"brew-cask:lens" = "latest"

# keepassxc
"flatpak:org.keepassxc.KeePassXC" = "latest"
"brew-cask:keepassxc"             = "latest"

# cursor
"apt:cursor"                = "latest"
"dnf:cursor"                = "latest"
"brew-cask:cursor"          = "latest"

# discord
"flatpak:com.discordapp.Discord" = "latest"
"brew-cask:discord"              = "latest"

[tools]
# --- AI CLI Tools ---
"npm:skills"                      = "latest"
"npm:@github/copilot"                    = "latest"
"npm:@google/gemini-cli"                 = "latest"
"npm:opencode-ai"                        = "latest"
"npm:@kilocode/cli"                      = "latest"
"npm:@mariozechner/pi-coding-agent"      = "latest"
"npm:@qwen-code/qwen-code"        = "latest"
"npm:@openai/codex"                      = "latest"
"npm:@anthropic-ai/claude-code"          = "latest"
