query($owner: String!, $repo: String!, $states: [PullRequestState!] = [OPEN], $limit: Int = 50, $orderBy: IssueOrderField = UPDATED_AT, $direction: OrderDirection = DESC) {
  repository(owner: $owner, name: $repo) {
    pullRequests(states: $states, first: $limit, orderBy: {field: $orderBy, direction: $direction}) {
      nodes {
        number
        title
        updatedAt
        reviewThreads(last: 50) {
          nodes {
            id
            isResolved
            comments(first: 1) {
              nodes {
                body
              }
            }
          }
        }
      }
    }
  }
}
