name: Lint Zsh Files
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.zsh'
  pull_request:
    paths:
      - '**/*.zsh'

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      
      - name: Install Zsh
        run: sudo apt-get update && sudo apt-get install -y zsh
      
      - name: Lint Zsh files
        run: find . -name "*.zsh" -not -path "./.git/*" -exec zsh -n {} \;
      
      - name: Check for syntax errors
        run: |
          if find . -name "*.zsh" -not -path "./.git/*" -exec zsh -n {} \; 2>&1 | grep -q "parse error"; then
            echo "Syntax errors found"
            exit 1
          else
            echo "All Zsh files passed syntax check"
          fi
