---
name: Test Dotfiles
on:
  push:
    paths:
      - 'src/**/*.zsh'
      - 'Makefile'
      - '.gitmodules'
      - '.stow-local-ignore'
  pull_request:
    paths:
      - 'src/**/*.zsh'
      - 'Makefile'
      - '.gitmodules'
      - '.stow-local-ignore'

jobs:
  test-linux:
    name: test-linux-${{ matrix.container }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - ubuntu:latest
          - debian:latest
          - fedora:latest
          - archlinux:latest
    container: ${{ matrix.container }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dotfiles using install.sh
      - name: Install dotfiles
        run: |
          export DOTFILES="$(pwd)"
          export DOTFILES_SKIP_CHSHELL=1
          ./install.sh

  test-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      # Install Homebrew
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dotfiles using install.sh
      - name: Install dotfiles
        run: |
          export DOTFILES="$(pwd)"
          export DOTFILES_SKIP_CHSHELL=1
          ./install.sh
